{
 "title": "story-dashboard",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": "label_values(tendermint_consensus_height, chain_id)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(tendermint_consensus_height{chain_id=\"$chain_id\"}, instance)"
   },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "$chain_id overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_height{chain_id=\"$chain_id\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_num_txs{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Avg Block Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_block_interval_seconds_sum{chain_id=\"$chain_id\", instance=\"$instance\" , job=\"$job\"}/tendermint_consensus_block_interval_seconds_count{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Bonded Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "tendermint_consensus_missing_validators{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "tendermint_consensus_byzantine_validators{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Online"
    },
    {
     "expr": "tendermint_consensus_missing_validators_power{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "tendermint_consensus_byzantine_validators_power{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Block Size"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tendermint_consensus_num_txs{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "instance overview: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Unconfirmed Transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_size{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Failed Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_failed_txs{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Recheck Times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_recheck_times{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Total Network Input",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "tendermint_p2p_peer_receive_bytes_total{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Total Network Output",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "tendermint_p2p_peer_send_bytes_total{chain_id=\"$chain_id\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  }
 ]
}